config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :screenings, only: [:create, :show, :new, :index]
  resources :user_steps
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/screening.rb
class Screening < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :authentication_keys => [:username]
  has_many :screenings
  validates :username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def home
  @screenings = Screening.where(user_id: current_user.id)
end

end

app/controllers/screenings_controller.rb
class ScreeningsController < ApplicationController

  def new
    @screening = Screening.new
  end

  def create
    @screening = Screening.new(screening_params)
    @screening.user = current_user
    @screening.save
    redirect_to root_path
  end

  def show
    @screening = Screening.find(params[:id])
  end

  def index
    @screenings = Screening.where(user_id: current_user.id)
    @json = @screenings.to_json
  end

  private

  def screening_params
    params.require(:screening).permit!
  end
end

app/controllers/user_steps_controller.rb
class UserStepsController < ApplicationController
  include Wicked::Wizard

  steps :selbstdarstellung, :affektive, :soziale, :kognitive, :lebenspraktischer

  def show
    @screening = Screening.new
    render_wizard
  end

  def update
    #@screening = Screening.find(params[:id])
    @screening.attributes = params[:screening]
    render_wizard @screening
  end

  def create
    @screening = Screening.new(screening_params)
    @screening.user_id = current_user.id
    @screening.save
  end

  private

  def screening_params
    params.require(:screening).permit!
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/scrennings_helper.rb
module ScrenningsHelper
end

app/helpers/user_steps_helper.rb
module UserStepsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LFP</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Lübecker Fähigkeiten Profil</h1>

<h2>Insgesamt <%= @screenings.count %> Profile</h2>
<ul>
<% @screenings.each do |screening| %>
  <li><%= link_to "Profil vom #{screening.created_at.strftime("%d %b %Y")}", screening_path(screening)%></li>
<% end %>
</ul>

app/views/screenings/index.html.erb
<h1>Auswertung</h1>
<div class="container" id="werte">
  <div class="cardwrapper-small">
    <div class="category-small">
      <strong>Selbstdarstellung / Selbstwahrnehmung</strong>
    </div>
    <div class="items">
      <a href="" id="Fantasie">Fantasie</a>
      <a href="" id="Realitaetsbezug">Realitätsbezug</a>
      <a href="" id="Selbstbild">Selbstbild</a>
      <a href="" id="Gefuehle">Wahrnehmen und Äußern eigener Gefühle und Bedürfnisse</a>
    </div>
  </div>
  <div class="cardwrapper-small">
    <div class="category-small">
      <strong>affektive / emotionale Fähigkeiten</strong>
    </div>
    <div class="items">
      <a href="" id="Schwingungsfaehigkeit">Schwingungsfähigkeit</a>
      <a href="" id="Aggressivitaet">Aggressivität</a>
      <a href="" id="Frustrationstoleranz">Frustrationstoleranz</a>
      <a href="" id="Stimmung">Stimmung / Gefühlslage</a>
      <a href="" id="Motivation">Motivation</a>
    </div>
  </div>
  <div class="cardwrapper-small">
    <div class="category-small">
      <strong>soziale Fähigkeiten</strong>
    </div>
    <div class="items">
      <a href="" id="Durchsetzung">Durchsetzungsvermögen</a>
      <a href="" id="Kontaktaufnahme">Kontaktaufnahme</a>
      <a href="" id="Regeln">Regeln einhalten</a>
      <a href="" id="Teamarbeit">Teamarbeit / Kooperation</a>
      <a href="" id="Kritik">Umgang mit Kritik</a>
    </div>
  </div>
  <div class="cardwrapper-small">
    <div class="category-small">
      <strong>kognitive Fähigkeiten</strong>
    </div>
    <div class="items">
      <a href="" id="Aufmerksamkeit">Aufmerksamkeit</a>
      <a href="" id="Ausdauer">Ausdauer</a>
      <a href="" id="Konzentration">Konzentration</a>
      <a href="" id="Merkfaehigkeit">Merkfähigkeit</a>
      <a href="" id="sensWahrnehmun">sensorische Wahrnehmung</a>
      <a href="" id="Flexibilitaet">Flexibilität</a>
    </div>
  </div>
  <div class="cardwrapper-small">
    <div class="category-small">
      <strong>lebenspraktischer Bereich</strong>
    </div>
    <div class="items">
      <a href="" id="Antrieb">Antrieb</a>
      <a href="" id="Ausdauer">Ausdauer</a>
      <a href="" id="Entscheidungsfaehigkeit">Entscheidungsfähigkeit</a>
      <a href="" id="Feinmotorik">Feinmotorik</a>
      <a href="" id="Selbstkontrolle">kritische Selbstkontrolle</a>
      <a href="" id="Problemloesen">Problemlösen</a>
      <a href="" id="Sorgfalt">Sorgfalt</a>
    </div>
  </div>
</div>

<canvas id="line-chart" width="600" height="200"></canvas>

<script>
  var userchoice = document.getElementById("werte");
  var chartData = <%= raw @json %>;
  userchoice.addEventListener("click", (event) => {
    arrayX = [];
    arrayY = [];
    var wert = event.target.id
    for (i = 0; i < chartData.length; i++) {
      var date = chartData[i].created_at;
      date = date.split("T")[0];
      arrayX.push(date);
      arrayY.push(chartData[i][wert]);
    } ;
    console.log(arrayY);
    event.preventDefault();
    new Chart(document.getElementById("line-chart"), {
      type: 'line',
      data: {
        labels: arrayX,
        datasets: [{
            data: arrayY,
            label: `${wert}`,
            borderColor: "#3e95cd",
            fill: false
          }
        ]
      },
      options: {
        scales: {
          yAxes: [{
            ticks: {
                stepSize: 1
            }
          }]
        },
        title: {
          display: true,
          text: 'LFP'
        }
      }
    });
  });
</script>

app/views/screenings/new.html.erb
<div >
<h1>Neues Profil</h1>

<%= form_for @screening do |f| %>
  <div class="container">
    <div class="cardwrapper">
      <div class="category">
        <h2>Selbstdarstellung / Selbstwahrnehmung</h2>
      </div>
      <%= f.label :'Fantasie:'%><br>
      <%= f.radio_button :Fantasie, 1%>1
      <%= f.radio_button :Fantasie, 2%>2
      <%= f.radio_button :Fantasie, 3%>3
      <%= f.radio_button :Fantasie, 4%>4
      <%= f.radio_button :Fantasie, 5%>5
      <br>
      <%= f.label :'Realitätsbezug:'%><br>
      <%= f.radio_button :Realitaetsbezug, 1%>1
      <%= f.radio_button :Realitaetsbezug, 2%>2
      <%= f.radio_button :Realitaetsbezug, 3%>3
      <%= f.radio_button :Realitaetsbezug, 4%>4
      <%= f.radio_button :Realitaetsbezug, 5%>5
      <br>
      <%= f.label :'Selbstbild:'%><br>
      <%= f.radio_button :Selbstbild, 1%>1
      <%= f.radio_button :Selbstbild, 2%>2
      <%= f.radio_button :Selbstbild, 3%>3
      <%= f.radio_button :Selbstbild, 4%>4
      <%= f.radio_button :Selbstbild, 5%>5
      <br>
      <%= f.label :'Wahrnehmen und Äußern eigener Gefühle und Bedürfnisse:' %><br>
      <%= f.radio_button :Gefuehle, 1%>1
      <%= f.radio_button :Gefuehle, 2%>2
      <%= f.radio_button :Gefuehle, 3%>3
      <%= f.radio_button :Gefuehle, 4%>4
      <%= f.radio_button :Gefuehle, 5%>5
    </div>

    <div class="cardwrapper">
      <div class="category">
        <h2>affektive / emotionale Fähigkeiten</h2>
      </div>
      <%= f.label :'affektive Schwingungsfähigkeit:'%><br>
      <%= f.radio_button :Schwingungsfaehigkeit, 1%>1
      <%= f.radio_button :Schwingungsfaehigkeit, 2%>2
      <%= f.radio_button :Schwingungsfaehigkeit, 3%>3
      <%= f.radio_button :Schwingungsfaehigkeit, 4%>4
      <%= f.radio_button :Schwingungsfaehigkeit, 5%>5
      <br>
      <%= f.label :'Aggressivität:'%><br>
      <%= f.radio_button :Aggressivitaet, 1%>1
      <%= f.radio_button :Aggressivitaet, 2%>2
      <%= f.radio_button :Aggressivitaet, 3%>3
      <%= f.radio_button :Aggressivitaet, 4%>4
      <%= f.radio_button :Aggressivitaet, 5%>5
      <br>
      <%= f.label :'Frustrationstoleranz:'%><br>
      <%= f.radio_button :Frustrationstoleranz, 1%>1
      <%= f.radio_button :Frustrationstoleranz, 2%>2
      <%= f.radio_button :Frustrationstoleranz, 3%>3
      <%= f.radio_button :Frustrationstoleranz, 4%>4
      <%= f.radio_button :Frustrationstoleranz, 5%>5
      <br>
      <%= f.label :'Stimmung / Gefühlslage:'%><br>
      <%= f.radio_button :Stimmung, 1%>1
      <%= f.radio_button :Stimmung, 2%>2
      <%= f.radio_button :Stimmung, 3%>3
      <%= f.radio_button :Stimmung, 4%>4
      <%= f.radio_button :Stimmung, 5%>5
      <br>
      <%= f.label :'Motivation:'%><br>
      <%= f.radio_button :Motivation, 1%>1
      <%= f.radio_button :Motivation, 2%>2
      <%= f.radio_button :Motivation, 3%>3
      <%= f.radio_button :Motivation, 4%>4
      <%= f.radio_button :Motivation, 5%>5
    </div>

    <div class="cardwrapper">
      <div class="category">
        <h2>soziale Fähigkeiten</h2>
      </div>
      <%= f.label :'Durchsetzungsvermögen:'%><br>
      <%= f.radio_button :Durchsetzung, 1%>1
      <%= f.radio_button :Durchsetzung, 2%>2
      <%= f.radio_button :Durchsetzung, 3%>3
      <%= f.radio_button :Durchsetzung, 4%>4
      <%= f.radio_button :Durchsetzung, 5%>5
      <br>
      <%= f.label :'Kontaktaufnahme:'%><br>
      <%= f.radio_button :Kontaktaufnahme, 1%>1
      <%= f.radio_button :Kontaktaufnahme, 2%>2
      <%= f.radio_button :Kontaktaufnahme, 3%>3
      <%= f.radio_button :Kontaktaufnahme, 4%>4
      <%= f.radio_button :Kontaktaufnahme, 5%>5
      <br>
      <%= f.label :'Regeln einhalten:'%><br>
      <%= f.radio_button :Regeln, 1%>1
      <%= f.radio_button :Regeln, 2%>2
      <%= f.radio_button :Regeln, 3%>3
      <%= f.radio_button :Regeln, 4%>4
      <%= f.radio_button :Regeln, 5%>5
      <br>
      <%= f.label :'Teamarbeit / Kooperation:'%><br>
      <%= f.radio_button :Teamarbeit, 1%>1
      <%= f.radio_button :Teamarbeit, 2%>2
      <%= f.radio_button :Teamarbeit, 3%>3
      <%= f.radio_button :Teamarbeit, 4%>4
      <%= f.radio_button :Teamarbeit, 5%>5
      <br>
      <%= f.label :'Kritik:'%><br>
      <%= f.radio_button :Kritik, 1%>1
      <%= f.radio_button :Kritik, 2%>2
      <%= f.radio_button :Kritik, 3%>3
      <%= f.radio_button :Kritik, 4%>4
      <%= f.radio_button :Kritik, 5%>5
    </div>

    <div class="cardwrapper">
      <div class="category">
        <h2>kognitive Fähigkeiten</h2>
      </div>
      <%= f.label :'Aufmerksamkeit:'%><br>
      <%= f.radio_button :Aufmerksamkeit, 1%>1
      <%= f.radio_button :Aufmerksamkeit, 2%>2
      <%= f.radio_button :Aufmerksamkeit, 3%>3
      <%= f.radio_button :Aufmerksamkeit, 4%>4
      <%= f.radio_button :Aufmerksamkeit, 5%>5
      <br>
      <%= f.label :'Ausdauer:'%><br>
      <%= f.radio_button :Ausdauer, 1%>1
      <%= f.radio_button :Ausdauer, 2%>2
      <%= f.radio_button :Ausdauer, 3%>3
      <%= f.radio_button :Ausdauer, 4%>4
      <%= f.radio_button :Ausdauer, 5%>5
      <br>
      <%= f.label :'Konzentration:'%><br>
      <%= f.radio_button :Konzentration, 1%>1
      <%= f.radio_button :Konzentration, 2%>2
      <%= f.radio_button :Konzentration, 3%>3
      <%= f.radio_button :Konzentration, 4%>4
      <%= f.radio_button :Konzentration, 5%>5
      <br>
      <%= f.label :'Merkfähigkeit:'%><br>
      <%= f.radio_button :Merkfaehigkeit, 1%>1
      <%= f.radio_button :Merkfaehigkeit, 2%>2
      <%= f.radio_button :Merkfaehigkeit, 3%>3
      <%= f.radio_button :Merkfaehigkeit, 4%>4
      <%= f.radio_button :Merkfaehigkeit, 5%>5
      <br>
      <%= f.label :'sensorische Wahrnehmung:'%><br>
      <%= f.radio_button :sensWahrnehmun, 1%>1
      <%= f.radio_button :sensWahrnehmun, 2%>2
      <%= f.radio_button :sensWahrnehmun, 3%>3
      <%= f.radio_button :sensWahrnehmun, 4%>4
      <%= f.radio_button :sensWahrnehmun, 5%>5
      <br>
      <%= f.label :'Sebstständigkeit:'%><br>
      <%= f.radio_button :Selbststaendigkeit, 1%>1
      <%= f.radio_button :Selbststaendigkeit, 2%>2
      <%= f.radio_button :Selbststaendigkeit, 3%>3
      <%= f.radio_button :Selbststaendigkeit, 4%>4
      <%= f.radio_button :Selbststaendigkeit, 5%>5
      <br>
      <%= f.label :'Flexibilität:'%><br>
      <%= f.radio_button :Flexibilitaet, 1%>1
      <%= f.radio_button :Flexibilitaet, 2%>2
      <%= f.radio_button :Flexibilitaet, 3%>3
      <%= f.radio_button :Flexibilitaet, 4%>4
      <%= f.radio_button :Flexibilitaet, 5%>5
    </div>

    <div class="cardwrapper">
      <div class="category">
        <h2>lebenspraktischer Bereich</h2>
      </div>
      <%= f.label :'Antrieb:'%><br>
      <%= f.radio_button :Antrieb, 1%>1
      <%= f.radio_button :Antrieb, 2%>2
      <%= f.radio_button :Antrieb, 3%>3
      <%= f.radio_button :Antrieb, 4%>4
      <%= f.radio_button :Antrieb, 5%>5
      <br>
      <%= f.label :'Entscheidungsfähigkeit:'%><br>
      <%= f.radio_button :Entscheidungsfaehigkeit, 1%>1
      <%= f.radio_button :Entscheidungsfaehigkeit, 2%>2
      <%= f.radio_button :Entscheidungsfaehigkeit, 3%>3
      <%= f.radio_button :Entscheidungsfaehigkeit, 4%>4
      <%= f.radio_button :Entscheidungsfaehigkeit, 5%>5
      <br>
      <%= f.label :'Feinmotorik:'%><br>
      <%= f.radio_button :Feinmotorik, 1%>1
      <%= f.radio_button :Feinmotorik, 2%>2
      <%= f.radio_button :Feinmotorik, 3%>3
      <%= f.radio_button :Feinmotorik, 4%>4
      <%= f.radio_button :Feinmotorik, 5%>5
      <br>
      <%= f.label :'kritische Selbstkontrolle:'%><br>
      <%= f.radio_button :Selbstkontrolle, 1%>1
      <%= f.radio_button :Selbstkontrolle, 2%>2
      <%= f.radio_button :Selbstkontrolle, 3%>3
      <%= f.radio_button :Selbstkontrolle, 4%>4
      <%= f.radio_button :Selbstkontrolle, 5%>5
      <br>
      <%= f.label :'Problemlösen:'%><br>
      <%= f.radio_button :Problemloesen, 1%>1
      <%= f.radio_button :Problemloesen, 2%>2
      <%= f.radio_button :Problemloesen, 3%>3
      <%= f.radio_button :Problemloesen, 4%>4
      <%= f.radio_button :Problemloesen, 5%>5
      <br>
      <%= f.label :'Sorgfalt:'%><br>
      <%= f.radio_button :Sorgfalt, 1%>1
      <%= f.radio_button :Sorgfalt, 2%>2
      <%= f.radio_button :Sorgfalt, 3%>3
      <%= f.radio_button :Sorgfalt, 4%>4
      <%= f.radio_button :Sorgfalt, 5%>5
    </div>
  </div>
<%= f.submit "Fertig" %>
<% end %>
<ul style="list-style: none;">
Hinweise zur Benotung:
  <li>1: stark eingeschränkte Fähigkeiten</li>
  <li>2: eingeschränkte Fähigkeiten</li>
  <li>3: leicht eingeschränkte Fähigkeiten</li>
  <li>4: durchschnittliche Fähigkeiten</li>
  <li>5: ausgeprägte, sehr gute Fähigkeiten</li>
</ul>
</div>

app/views/screenings/show.html.erb
<h1>Profil vom <%= @screening.created_at.strftime("%d %b %Y") %></h1>
<div class="container">
  <div class="cardwrapper">
    <div class="category">
      <h2>Selbstdarstellung / Selbstwahrnehmung</h2>
    </div>
    <div class="items">
     <p>Fantasie: <%= @screening.Fantasie %></p>
     <p>Realitätsbezug: <%= @screening.Realitaetsbezug %></p>
     <p>Selbstbild: <%= @screening.Selbstbild %></p>
     <p>Wahrnehmen und Äußern eigener Gefühle und Bedürfnisse: <%= @screening.Gefuehle %></p>
    </div>
  </div>
  <div class="cardwrapper">
    <div class="category">
      <h2>affektive / emotionale Fähigkeiten</h2>
    </div>
    <div class="items">
      <p>affektive Schwingungsfähigkeit: <%= @screening.Schwingungsfaehigkeit %></p>
      <p>Aggressivität: <%= @screening.Aggressivitaet %></p>
      <p>Frustrationstoleranz: <%= @screening.Frustrationstoleranz %></p>
      <p>Stimmung / Gefühlslage: <%= @screening.Stimmung %></p>
      <p>Motivation: <%= @screening.Motivation %></p>
    </div>
  </div>
  <div class="cardwrapper">
    <div class="category">
      <h2>soziale Fähigkeiten</h2>
    </div>
    <div class="items">
      <p>Durchsetzungsvermögen: <%= @screening.Durchsetzung %></p>
      <p>Kontaktaufnahme: <%= @screening.Kontaktaufnahme %></p>
      <p>Regeln einhalten: <%= @screening.Regeln %></p>
      <p>Teamarbeit / Kooperation: <%= @screening.Teamarbeit %></p>
      <p>Umgang mit Kritik: <%= @screening.Kritik %></p>
    </div>
  </div>
  <div class="cardwrapper">
    <div class="category">
      <h2>kognitive Fähigkeiten</h2>
    </div>
    <div class="items">
      <p>Aufmerksamkeit: <%= @screening.Aufmerksamkeit %></p>
      <p>Ausdauer: <%= @screening.Ausdauer %></p>
      <p>Konzentration: <%= @screening.Konzentration %></p>
      <p>Merkfähigkeit: <%= @screening.Merkfaehigkeit %></p>
      <p>sensorische Wahrnehmung: <%= @screening.sensWahrnehmun %></p>
      <p>Sebstständigkeit: <%= @screening.Selbststaendigkeit %></p>
      <p>Flexibilität: <%= @screening.Flexibilitaet %></p>
    </div>
  </div>
  <div class="cardwrapper">
    <div class="category">
      <h2>lebenspraktischer Bereich</h2>
    </div>
    <div class="items">
      <p>Antrieb: <%= @screening.Antrieb %></p>
      <p>Entscheidungsfähigkeit: <%= @screening.Entscheidungsfaehigkeit %></p>
      <p>Feinmotorik: <%= @screening.Feinmotorik %></p>
      <p>kritische Selbstkontrolle: <%= @screening.Selbstkontrolle %></p>
      <p>Problemlösen: <%= @screening.Problemloesen %></p>
      <p>Sorgfalt: <%= @screening.Sorgfalt %></p>
    </div>
  </div>
</div>

<a href="/" class="link"><span>zurück</span></a>

app/views/shared/_navbar.html.erb
<div class="navbar">
<%= link_to root_path do %>
  <%= image_tag 'home.png', class: 'icon-link' %>
<% end %>
<%= link_to new_screening_path do %>
  <%= image_tag 'plus.png', class: 'icon-link' %>
<% end %>
<%= link_to screenings_path do %>
  <%= image_tag 'data.png', class: 'icon-link' %>
<% end %>

<%= link_to 'Logout', destroy_user_session_path, class: 'icon-link', method: :delete %>
</div>

app/views/user_steps/affektive.html.erb
<h1>affektive / emotionale Fähigkeiten</h1>

<%= form_for @screening, url: wizard_path do |f| %>
<%= f.label :'affektive Schwingungsfähigkeit'%>
<%= f.number_field 'Schwingungsfaehigkeit', in: 1...6 %>
<%= f.label :Realitätsbezug%>
<%= f.number_field 'Aggressivitaet', in: 1...6 %>
<%= f.label :Selbstbild%>
<%= f.number_field 'Frustrationstoleranz', in: 1...6 %>
<%= f.label :'Stimmung / Gefühlslage' %>
<%= f.number_field 'Stimmung', in: 1...6 %>
<%= f.label :Motivation %>
<%= f.number_field 'Motivation', in: 1...6 %>

<%= f.submit "weiter" %>
<% end %>

app/views/user_steps/selbstdarstellung.html.erb
<h1>Selbstdarstellung / Selbstwahrnehmung</h1>

<%= form_for @screening, url: wizard_path, method: :put do |f| %>
<%= f.label :Fantasie%>
<%= f.number_field 'Fantasie', in: 1...6 %>
<%= f.label :Realitätsbezug%>
<%= f.number_field 'Realitaetsbezug', in: 1...6 %>
<%= f.label :Selbstbild%>
<%= f.number_field 'Selbstbild', in: 1...6 %>
<%= f.label :'Wahrnehmen und Äußern eigener Gefühle und Bedürfnisse' %>
<%= f.number_field 'Gefuehle', in: 1...6 %>

<%= f.submit "weiter" %>
<% end %>